language: ruby
addons:
  code_climate:
    repo_token: cedc6c0daf215ad9c9977b06c3ecd18cb5c0e00004ea6de744cec7243002fa9f
rvm:
- 2.1
- 2.2
- ruby-head
before_install:
- gem install bundle
install:
- bundle install
script:
- bundle exec rspec
