#!/usr/bin/env ruby
# Creates an owner for Scarlet.
require 'bundler/setup'
require 'scarlet/models/nick'

name = ARGV.shift

if nick = Scarlet::Nick.owner
  if name == nick.nick
    puts "You (#{name}) are the owner..."
  else
    puts "#{nick.nick} is currently the owner!"
  end
  exit
end

if nick = Scarlet::Nick.first(nick: name)
  nick.groups << 'root'
  nick.save
  puts "Successfuly set #{nick.nick} as owner."
else
  puts "No user #{name} exists! Register first with Scarlet (use !register in the channel)."
end
